machineFields = ['ID','Machine Name', 'Machine Image', 'Machine Link', 'Bond Placement Repeatability','Bonding Area','Loop Types', 'UPH', 'XY Resolution', 'Z Resolution', 'Fine Pitch Capability', 'Loop Height Variation', 'Wire Length', 'Wire Capacity', 'Optics Lens Magnification', 'S-Scan Vision Engine', 'Recognition Range', 'Reference Systems', 'Camera Type', 'Depth Of Field', 'Die Rotation', 'XY Motors Type', 'L/F Width', 'L/F Length', 'L/F Thickness', 'Die Site Indexing Pitch', 'No.of Magazine', 'No. of Levels', 'Magazine Width', 'Magazine Length', 'Magazine Height', 'Slot Pitch (Range of Pitch)', 'Spool Diameter', 'Spool Width', 'Wire Count', 'Wire End', 'Drive Motor Type', 'Wire Clamp', 'Bond Time Range', 'Ultrasonic Mode', 'Transducer Frequency', 'Man Machine Interface', 'Storage Media', 'Power Input', 'Power Consumption', 'Minimum Air Pressure', 'Air Consumption', 'Air Quality', 'Environmental Requirement', 'Machine Outline', 'Machine Weight', 'Machine Shipping Weight', 'Indexers', 'Material Handling Kits', 'Heavy Wire Kit', 'Illumination Kit', 'QFN Kit', 'Cu Application', 'Easy CU Conversion', 'Smart PR', 'Easy Cu Looping', 'Smart Wire Handler', 'Auto Wire Rethread'];

icMachines = [
{
		//eagleAERO
		machineName: 'Eagle AERO',
		machineImage: 'img/wb/ic/eagleAero.png',
		machineLink: '../html/Wire Bonders Products/Eagle Aero.html',
		bondPlacement: '±2.0 µm @ 3-sigma',
		bondingArea: '56mm x 90mm (LF width <=100mm)',
		loopTypes: 'ECP Loop Profile up to 15 kinks',
		uPH: '24 wires/sec for 2mm',
		xyResolution: '10 nm',
		zResolution: '10 nm',
		finePitchCapability: '30 µm BPP',
		loopHeightVariation: '2 mil (Ultra Low Loop) - 16 mil',
		wireLength: '0.2 - 8 mm',
		wireCapacity: 'Up to 10000 for Step Repeat Matrix',
		opticsLensMagnification: 'Programmable Focus:<br>Dual optical path 8X and 2X <br>PR Look-Ahead:<br>Dual optical path 5.2X and 1X',
		sScanVisionEngine: '-',
		recognitionRange: '± 2.5 mil<br>X & Y± 10°(programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField:'-',
		dieRotation:'-',
		xyMotorsType:'Multi-phase linear motor and fully programmable(Handle multi-type devices)',
		lfWidth:'28 - 105 mm',
		lfLength:'140 - 300mm',
		lfThickness:'0.1 - 0.8 mm',
		dieSiteIndexingPitch:'-',
		noOfMagazine:'3 (40 levels with 0.1" pitch / 2.54mm)',
		noOfLevels:'Programmable',
		magazineWidth:'32 - 115 mm',
		magazineLength:'140 - 30 5mm',
		magazineHeight:'180 mm (max)',
		slotPitch:'2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth:'50 mm<br>25mm as option',
		wireCount:'Yes',
		wireEnd:'Yes',
		driveMotorType:'Voice coil motor',
		wireClamp:'Piezo driven, pivot-less mechanism',
		bondTimeRange:'-',
		ultrasonic:'Constant Current, Constant Voltage, Constant Power',
		transducerFreq:'Dual frequencies',
		manMachineInterface:'Windows-based GUI',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption:'1200 VA / 1200 Watt',
		minAirPressure:'-',
		airConsumption:'minimum 5 BAR, 150 lpm, Inlet tube OD 12mm',
		airQuality:'-',
		environmentalRequirement:'-',
		machineOutline:'1200mm (width) x 990mm (length) x 1760mm (height)',
		machineWeight:'800 Kg',
		machineShippingWeight:'-',
		indexers:'Yes',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'NA',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//ihawkAERO		
		machineName: 'iHawk AERO',
		machineImage: 'img/wb/ic/ihawk-aero.png',
		machineLink: '../html/Wire Bonders Products/iHawk Aero.html',
		bondPlacement: '±2.0 µm @ 3-sigma',
		bondingArea: '56mm x 90mm (LF width <=100mm)',
		loopTypes: 'ECP Loop Profile up to 15 kinks',
		uPH: '24 wires/sec for 2mm',
		xyResolution: '10 nm',
		zResolution: '10 nm',
		finePitchCapability: '-',
		loopHeightVariation: '2 mil (Ultra Low Loop) - 16 mil',
		wireLength: '0.2 - 8 mm',
		wireCapacity: 'Up to 10000 for Step Repeat Matrix',
		opticsLensMagnification: 'Dual optical path 5.2X and 1X',
		sScanVisionEngine: '-',
		recognitionRange: '±2.5 mil<br>X & Y± 10°(programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField:'-',
		dieRotation:'-',
		xyMotorsType:'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth:'28 - 105 mm',
		lfLength:'140 - 300mm',
		lfThickness:'0.1 - 0.8 mm',
		dieSiteIndexingPitch:'-',
		noOfMagazine:'3 (40 levels with 0.1" pitch / 2.54mm)',
		noOfLevels:'Programmable',
		magazineWidth:'32 - 115 mm',
		magazineLength:'140 - 305mm',
		magazineHeight:'180 mm (max)',
		slotPitch:'2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth:'50 mm<br>25mm as option',
		wireCount:'Yes',
		wireEnd:'Yes',
		driveMotorType:'Voice coil motor',
		wireClamp:'Piezo driven, pivot-less mechanism',
		bondTimeRange:'-',
		ultrasonic:'Constant Current, Constant Voltage, Constant Power',
		transducerFreq:'Dual frequencies',
		manMachineInterface:'Windows-based GUI',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption:'1200 VA / 1200 Watt',
		minAirPressure:'-',
		airConsumption:'minimum 5 BAR, 150 lpm, Inlet tube OD 12mm',
		airQuality:'-',
		environmentalRequirement:'-',
		machineOutline:'1200mm (width) x 990mm (length) x 1760mm (height)',
		machineWeight:'800 Kg',
		machineShippingWeight:'-',
		indexers:'Yes',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'NA',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//twineagleXpressGoCu	
		machineName: 'TwinEagle Xpress GoCu',
		machineImage: 'img/wb/ic/twineagle-xpress-gocu.png',
		machineLink: '../html/Wire Bonders Products/TwinEagle Xpress GoCu.html',
		bondPlacement: 'PFM: ±2.0 µm @ 3-sigma<br>PRLA: ±3.0 µm @ 3-sigma',
		bondingArea: '56mm x 90mm (LF width <=100mm)',
		loopTypes: 'EasGo, EasiCu (Model Based)',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '50 nm',
		zResolution: '40 nm',
		finePitchCapability: '30 µm BPP (Au)<br>40 µm BPP (Cu)',
		loopHeightVariation: '2.0 - 16.0 mil',
		wireLength: '0.6 - 7 mm',
		wireCapacity: 'Up to 5000',
		opticsLensMagnification: 'PFM, Single & Dual path PRLA',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CMOS',
		depthOfField: '-',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '30 - 100 mm',
		lfLength: '140 - 300mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1" pitch / 2.54mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '30 - 105 mm',
		magazineLength: '140 - 305mm',
		magazineHeight: '55 - 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 2000W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '960mm (width) x 1320mm (length) x 2100mm (height)',
		machineWeight:'1050 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'Yes',
		smartPR:'Yes',
		easyCuLooping:'NA',
		smartWire:'Yes',
		autoWireRethread:'Capable',
	},

	{
		//iHawk Xpress GoCu
		machineName: 'iHawk Xpress GoCu',
		machineImage: 'img/wb/ic/ihawk-xpress-gocu.png',
		machineLink: '../html/Wire Bonders Products/iHawk Xpress GoCu.html',
		bondPlacement: '3.0 µm @ 3-sigma',
		bondingArea: '56mm x 90mm (LF width <=100mm)',
		loopTypes: 'New looping modes (eg Easi 1st kink, 2nd kinks etc.) ',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '50 nm',
		zResolution: '40 nm',
		finePitchCapability: '50 µm BPP',
		loopHeightVariation: '3 - 16 mil',
		wireLength: 'Max 8 mm',
		wireCapacity: 'Up to 5000',
		opticsLensMagnification: 'Single path optics, 2x- 4x adjustable magnification<br>Dual path optics as option',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField: '-',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '30 - 100 mm',
		lfLength: '140 - 300mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: 'Typically 2-3',
		noOfLevels: 'Programmable',
		magazineWidth: '30 - 105 mm',
		magazineLength: '140 - 305mm',
		magazineHeight: 'Max. 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Multi-Lingual',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 820mm (length) x 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'Yes',
		smartPR:'Yes',
		easyCuLooping:'NA',
		smartWire:'Yes',
		autoWireRethread:'Capable',
	},

	{
		//Eagle Xpress GoCu
		machineName: 'Eagle Xpress GoCu',
		machineImage: 'img/wb/ic/eagle-xpress-gocu.png',
		machineLink: '../html/Wire Bonders Products/Eagle Xpress GoCu.html',
		bondPlacement: '±2.0 µm @ 3-sigma',
		bondingArea: '56mm x 90mm (LF width <=100mm)',
		loopTypes: 'New looping modes (eg Easi 1st kink, 2nd kinks etc.) ',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '50 nm',
		zResolution: '40 nm',
		finePitchCapability: '30 µm BPP',
		loopHeightVariation: '3 - 16 mil',
		wireLength: '0.6 - 7 mm',
		wireCapacity: '3000',
		opticsLensMagnification: 'Programmable Focus Optics 8X and 2.0X',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField: '-',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '30 - 105 mm',
		lfLength: '140 - 300mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1" pitch / 2.54mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '30 - 105 mm',
		magazineLength: '140 - 305mm',
		magazineHeight: '55 - 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 820mm (length) x 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'Yes',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Available',
		easyCuConversion:'Yes',
		smartPR:'Yes',
		easyCuLooping:'Yes',
		smartWire:'Yes',
		autoWireRethread:'Capable',
	},

	{
		//TwinEagle Xtreme GoCu
		machineName: 'TwinEagle Xtreme GoCu',
		machineImage: 'img/wb/ic/eagle-xpress-gocu.png',
		machineLink: '../html/Wire Bonders Products/Eagle Xpress GoCu.html',
		bondPlacement: 'PFM: ±2.0 mm @ 3 Sigma<br>PRLA: ±3.0 mm @ 3 Sigma',
		bondingArea: '56mm x 70mm (LF width<=80mm)',
		loopTypes: 'EasGo, EasiCu ( Model Based )',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '50 nm',
		zResolution: '100 nm',
		finePitchCapability: '30 µm BPP',
		loopHeightVariation: '2 - 16 mil',
		wireLength: 'Max 8 mm',
		wireCapacity: 'Up to 5000',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CMOS',
		depthOfField: '-',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '29 - 90 mm',
		lfLength: '140 - 240mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1" pitch / 2.54mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '30 - 100 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: '55 - 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Multi-Lingual',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 960mm (length) x 1600mm (height)',
		machineWeight:'1020 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'Yes',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'Yes',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//iHawk Xtreme GoCu
		machineName: 'iHawk Xtreme GoCu',
		machineImage: 'img/wb/ic/ihawk-xtreme-gocu.png',
		machineLink: '../html/Wire Bonders Products/iHawk Xtreme GoCu.html',
		bondPlacement: '±2.0 µm @ 3 Sigma',
		bondingArea: '56mm x 70mm (LF width<=80mm)',
		loopTypes: '-',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '100 nm',
		zResolution: '200 nm',
		finePitchCapability: '-',
		loopHeightVariation: '-',
		wireLength: 'Max 8 mm',
		wireCapacity: 'Up to 5000',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CMOS',
		depthOfField: '-',
		dieRotation: '-',
		xyMotorsType: '-',
		lfWidth: '23 - 90 mm',
		lfLength: '140 - 295mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: 'Typically 2-3',
		noOfLevels: '-',
		magazineWidth: '30 - 100 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: '55 - 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'-',
		spoolWidth: '-',
		wireCount: '-',
		wireEnd: '-',
		driveMotorType: '-',
		wireClamp: '-',
		bondTimeRange: '-',
		ultrasonic: '-',
		transducerFreq: 'Mode A: 138kHz<br>Mode B: 73kHz',
		manMachineInterface: 'Multi-Lingual',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 820mm (length) x 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//Harrier Xtreme GoCu
		machineName: 'Harrier Xtreme GoCu',
		machineImage: 'img/wb/ic/harrier-xtreme-gocu.png',
		machineLink: '../html/Wire Bonders Products/Harrier Xtreme GoCu.html',
		bondPlacement: '±2.0 µm @ 3 Sigma',
		bondingArea: '56mm x 70mm (LF width<=80mm)',
		loopTypes: '-',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '100 nm',
		zResolution: '200 nm',
		finePitchCapability: '-',
		loopHeightVariation: '-',
		wireLength: 'Max 8 mm',
		wireCapacity: 'Up to 5000',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: '-',
		depthOfField: '-',
		dieRotation: '-',
		xyMotorsType: '-',
		lfWidth: '23 - 90 mm',
		lfLength: '140 - 240mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: 'Typically 2-3',
		noOfLevels: '-',
		magazineWidth: '30 - 100 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: '55 - 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'-',
		spoolWidth: '-',
		wireCount: '-',
		wireEnd: '-',
		driveMotorType: '-',
		wireClamp: '-',
		bondTimeRange: '-',
		ultrasonic: '-',
		transducerFreq: 'Mode A: 138kHz<br>Mode B: 73kHz',
		manMachineInterface: 'Multi-Lingual',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 2000W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 960mm (length) x 1600mm (height)',
		machineWeight:'1020 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//Eagle Xtreme GoCu
		machineName: 'Eagle Xtreme GoCu',
		machineImage: 'img/wb/ic/eagle-xtreme-gocu.png',
		machineLink: '../html/Wire Bonders Products/Eagle Xtreme GoCu.html',
		bondPlacement: 'PFM: ±2.0 µm @ 3 Sigma<br>PRLA: ±3.0µm @ 3 Sigma',
		bondingArea: '56mm x 70mm (LF width<=80mm)',
		loopTypes: '-',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '50 nm',
		zResolution: '100 nm',
		finePitchCapability: '30 µm BPP (Au)<br>40 µm BPP (Cu)',
		loopHeightVariation: '2 - 16 mil',
		wireLength: '0.6 - 7 mm',
		wireCapacity: 'Up to 5000',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CMOS',
		depthOfField: '-',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '23 - 90 mm',
		lfLength: '140 - 295mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
		noOfLevels: '-',
		magazineWidth: '30 - 100 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25 mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 820mm (length) x 1600mm (height)',
		machineWeight:'730 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},


	{
		//Eagle Xpress
		machineName: 'Eagle Xpress',
		machineImage: 'img/wb/ic/eagle-xpress.png',
		machineLink: '../html/Wire Bonders Products/Eagle Xpress.html',
		bondPlacement: '-',
		bondingArea: '-',
		loopTypes: '-',
		uPH: '-',
		xyResolution: '-',
		zResolution: '-',
		finePitchCapability: '-',
		loopHeightVariation: '-',
		wireLength: '-',
		wireCapacity: '-',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: '-',
		referenceSystems: '-',
		cameraType: '-',
		depthOfField:'-',
		dieRotation:'-',
		xyMotorsType:'-',
		lfWidth: '-',
		lfLength: '-',
		lfThickness: '-',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '-',
		noOfLevels: '-',
		magazineWidth: '-',
		magazineLength: '-',
		magazineHeight: '-',
		slotPitch: '-',
		spoolDiameter: '-',
		spoolWidth: '-',
		wireCount: '-',
		wireEnd: '-',
		driveMotorType: '-',
		wireClamp: '-',
		bondTimeRange:'-',
		ultrasonic: '-',
		transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
	},

	{
		//TwinEagle Xtreme
		machineName: 'TwinEagle Xtreme',
		machineImage: 'img/wb/ic/twineagle-xtreme.png',
		machineLink: '../html/Wire Bonders Products/TwinEagle Xtreme.html',
		bondPlacement: '±2.0 µm @ 3 Sigma',
		bondingArea: ' 56mm x 70mm (LF width<=80mm)<br>56mm x "Y" mm, where "Y" is equal to (150 - lead frame width) mm',
		loopTypes: '52 loop modes (eg Q-Loop, Sq-Loop, J-Loop, M-Loop etc)',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '50 nm',
		zResolution: '100 nm',
		finePitchCapability: '30 µm BPP',
		loopHeightVariation: '3 - 16 mil',
		wireLength: '0.6 - 8 mm',
		wireCapacity: '3000 (standard)',
		opticsLensMagnification: 'Dual optical path 8X and 2.0X<br>5.5 X and 2.0X as option',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField: '100 µm @ 8X<br>500 µm @ 2.0X<br>120 µm @ 5.5X as option',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '28 - 90 mm',
		lfLength: '140 - 295mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '30 - 100 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25 mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: '2000W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '730mm (width) x 910mm (length) x 1450mm (height)',
		machineWeight:'1020 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},

	{
		//Eagle Xtreme X2L
		machineName: 'Eagle Xtreme X2L',
		machineImage: 'img/wb/ic/eagle-xtreme-X2L.png',
		machineLink: '../html/Wire Bonders Products/Eagle Xtreme X2L.html',
		bondPlacement: '-',
		bondingArea: '-',
		loopTypes: '-',
		uPH: '-',
		xyResolution: '-',
		zResolution: '-',
		finePitchCapability: '-',
		loopHeightVariation: '-',
		wireLength: '-',
		wireCapacity: '-',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: '-',
		referenceSystems: '-',
		cameraType: '-',
		depthOfField:'-',
		dieRotation:'-',
		xyMotorsType:'-',
		lfWidth: '-',
		lfLength: '-',
		lfThickness: '-',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '-',
		noOfLevels: '-',
		magazineWidth: '-',
		magazineLength: '-',
		magazineHeight: '-',
		slotPitch: '-',
		spoolDiameter: '-',
		spoolWidth: '-',
		wireCount: '-',
		wireEnd: '-',
		driveMotorType: '-',
		wireClamp: '-',
		bondTimeRange:'-',
		ultrasonic: '-',
		transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
	},


	{
		//Eagle Xtreme R2R
		machineName: 'Eagle Xtreme R2R',
		machineImage: 'img/wb/ic/eagle-xtreme-R2R.png',
		machineLink: '../html/Wire Bonders Products/Eagle Xtreme R2R.html',
		bondPlacement: '-',
		bondingArea: '-',
		loopTypes: '-',
		uPH: '-',
		xyResolution: '-',
		zResolution: '-',
		finePitchCapability: '-',
		loopHeightVariation: '-',
		wireLength: '-',
		wireCapacity: '-',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: '-',
		referenceSystems: '-',
		cameraType: '-',
		depthOfField:'-',
		dieRotation:'-',
		xyMotorsType:'-',
		lfWidth: '-',
		lfLength: '-',
		lfThickness: '-',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '-',
		noOfLevels: '-',
		magazineWidth: '-',
		magazineLength: '-',
		magazineHeight: '-',
		slotPitch: '-',
		spoolDiameter: '-',
		spoolWidth: '-',
		wireCount: '-',
		wireEnd: '-',
		driveMotorType: '-',
		wireClamp: '-',
		bondTimeRange:'-',
		ultrasonic: '-',
		transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
	},

	{
		//Eagle Xtreme
		machineName: 'Eagle Xtreme',
		machineImage: 'img/wb/ic/eagle-xtreme.png',
		machineLink: '../html/Wire Bonders Products/Eagle Xtreme.html',
		bondPlacement: '±2.0 µm @ 3 Sigma',
		bondingArea: ' 56 mm x 70 mm (LF width <=80mm)',
		loopTypes: '52 loop modes<br>(eg Q-Loop, Sq-Loop, J-Loop, M-Loop etc)',
		uPH: '20 wires/sec for 2mm',
		xyResolution: '50 nm',
		zResolution: '100 nm',
		finePitchCapability: '30 µm BPP',
		loopHeightVariation: '3 - 16 mil',
		wireLength: '0.6 - 8 mm',
		wireCapacity: '3000 (standard)',
		opticsLensMagnification: 'Dual optical path 8X and 2.0X<br>5.5 X and 2.0X as option',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField: '100 µm @ 8X<br>730 µm @ 2.0X<br>120 µm @ 5.5X as option',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '23 - 90 mm',
		lfLength: '140 - 295mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '16 - 100 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25 mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) X 820mm (length) X 1600mm (height)',
		machineWeight:'730 Kg',
		machineShippingWeight:'850 Kg',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Upgradable',
		easyCuConversion:'Yes',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},

	{
		//Harrier
		machineName: 'Harrier',
		machineImage: 'img/wb/ic/harrier.png',
		machineLink: '../html/Wire Bonders Products/Harrier.html',
		bondPlacement: '±3.5 µm @ 3 Sigma',
		bondingArea: ' 56 mm x 65 mm (LF width <=72mm)',
		loopTypes: '28 loop modes (eg Q-Loop, Sq-Loop, J-Loop etc)',
		uPH: '60+ ms for 2 mm wire (Q-loop)',
		xyResolution: '400 nm',
		zResolution: '800 nm',
		finePitchCapability: '50 µm BPP',
		loopHeightVariation: '4 - 16 mil',
		wireLength: '0.6 - 8 mm',
		wireCapacity: '3000 (standard)',
		opticsLensMagnification: 'Single optical path 3X',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField: '100 µm @ 3X',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '23 - 90 mm',
		lfLength: '140 - 295mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '16 - 100 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25 mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1600W',
		minAirPressure: '-',
		airConsumption: '12 mm (ID)',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '888 mm (width) x 730 mm (length) x 1600 mm (height)',
		machineWeight:'1100 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'NA',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},

	{
		//iHawk
		machineName: 'iHawk',
		machineImage: 'img/wb/ic/ihawk.png',
		machineLink: '../html/Wire Bonders Products/iHawk.html',
		bondPlacement: '±3.0 µm @ 3 Sigma',
		bondingArea: ' 54 mm x 65 mm ',
		loopTypes: 'Advance loop control',
		uPH: '60 ms for 2 mm wire (Q-loop)',
		xyResolution: '200 nm',
		zResolution: '400 nm',
		finePitchCapability: '35 µm BPP',
		loopHeightVariation: '4 - 16 mil',
		wireLength: '0.6 - 8 mm',
		wireCapacity: '3000 (standard)',
		opticsLensMagnification: '2-4x manual zoom single optical path',
		sScanVisionEngine: '-',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField: '264 µm @ 4X<br>336 µm @ 2X',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
		lfWidth: '23 - 90 mm',
		lfLength: '140 - 295mm',
		lfThickness: '<= 0.5 mm (0.8mm optional)',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '33 - 100 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25 mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) X 820mm (length) X 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'NA',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},

	{
		//twineagle
		machineName: 'Twineagle',
		machineImage: 'img/wb/ic/twineagle.png',
		machineLink: '../html/Wire Bonders Products/TwinEagle.html',
		bondPlacement: '-',
		bondingArea: '-',
		loopTypes: '-',
		uPH: '-',
		xyResolution: '-',
		zResolution: '-',
		finePitchCapability: '-',
		loopHeightVariation: '-',
		wireLength: '-',
		wireCapacity: '-',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: '-',
		referenceSystems: '-',
		cameraType: '-',
		depthOfField:'-',
		dieRotation:'-',
		xyMotorsType:'-',
		lfWidth: '-',
		lfLength: '-',
		lfThickness: '-',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '-',
		noOfLevels: '-',
		magazineWidth: '-',
		magazineLength: '-',
		magazineHeight: '-',
		slotPitch: '-',
		spoolDiameter: '-',
		spoolWidth: '-',
		wireCount: '-',
		wireEnd: '-',
		driveMotorType: '-',
		wireClamp: '-',
		bondTimeRange:'-',
		ultrasonic: '-',
		transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
	},

	{
		//Eagle60-XL
		machineName: 'Eagle60-XL',
		machineImage: 'img/wb/ic/eagle60-XL.png',
		machineLink: '../html/Wire Bonders Products/Eagle60-XL.html',
		bondPlacement: '±3.5 µm @ 3 Sigma',
		bondingArea: ' 54 mm x 88 mm ',
		loopTypes: '52 loop modes<br>(eg Q-Loop, Sq-Loop, J-Loop, M-Loop etc)',
		uPH: '95 ms for 2 mm wire',
		xyResolution: 'Linear encoder with 0.2 micron resolution',
		zResolution: 'Encoder with 0.4 micron resolution',
		finePitchCapability: '50 µm BPP',
		loopHeightVariation: '4 - 16 mil',
		wireLength: '0.6 - 8 mm',
		wireCapacity: '3000',
		opticsLensMagnification: '5.5x/3.6x or 8x/3.6x',
		sScanVisionEngine: 'ASM MMX PRS which enables very fast PR with highly accurate and sophisticated pattern recognition algorithm',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField: '100 µm @ 8X<br>323.5X<br>120 µm @ 5.5X as option',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor',
		lfWidth: '60 - 110 mm',
		lfLength: 'Max 280 mm',
		lfThickness: '0.075 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '55 - 120 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25 mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) X 820mm (length) X 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'NA',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},

	{
		//Eagle60-X2L
		machineName: 'Eagle60-X2L',
		machineImage: 'img/wb/ic/eagle60-X2L.png',
		machineLink: '../html/Wire Bonders Products/Eagle60-X2L.html',
		bondPlacement: '±3.5 µm @ 3 Sigma',
		bondingArea: '54mm x 102mm (LF width <=124mm)<br>56mm x "Y" mm, where "Y" is equal to (226 - lead frame width) mm',
		loopTypes: '52 loop modes<br>(eg Q-Loop, Sq-Loop, J-Loop, M-Loop etc)',
		uPH: '90 ms for 2 mm wire',
		xyResolution: '200 nm',
		zResolution: '400 nm',
		finePitchCapability: '50 µm BPP',
		loopHeightVariation: '4 - 16 mil',
		wireLength: 'Max 8 mm',
		wireCapacity: '3000',
		opticsLensMagnification: 'Dual optical path 8X and 3.5X<br>5.5 X and 3.5X as option',
		sScanVisionEngine: 'ASM MMX PRS which enables very fast PR with highly accurate and sophisticated pattern recognition algorithm',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: '-',
		cameraType: 'CCD',
		depthOfField: '100 µm @ 8X<br>320 µm @ 3.5X<br>120 µm @ 5.5X as option',
		dieRotation: '-',
		xyMotorsType: 'Multi-phase linear motor and fully programmable(Handle multi-type devices)',
		lfWidth: '102 - 135 mm',
		lfLength: '140 - 295 mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
		noOfLevels: 'Programmable',
		magazineWidth: '60 - 140 mm',
		magazineLength: '140 - 295mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '50 mm<br>25 mm as option',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '1 - 255 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138kHz<br>64kHz or 100kHz as option',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) X 820mm (length) X 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'NA',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},

	{
		//Eagle60V
		machineName: 'Eagle60V',
		machineImage: 'img/wb/ic/eagle60V.png',
		machineLink: '../html/Wire Bonders Products/Eagle60V.html',
		bondPlacement: '-',
		bondingArea: '-',
		loopTypes: '-',
		uPH: '-',
		xyResolution: '-',
		zResolution: '-',
		finePitchCapability: '-',
		loopHeightVariation: '-',
		wireLength: '-',
		wireCapacity: '-',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: '-',
		referenceSystems: '-',
		cameraType: '-',
		depthOfField:'-',
		dieRotation:'-',
		xyMotorsType:'-',
		lfWidth: '-',
		lfLength: '-',
		lfThickness: '-',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '-',
		noOfLevels: '-',
		magazineWidth: '-',
		magazineLength: '-',
		magazineHeight: '-',
		slotPitch: '-',
		spoolDiameter: '-',
		spoolWidth: '-',
		wireCount: '-',
		wireEnd: '-',
		driveMotorType: '-',
		wireClamp: '-',
		bondTimeRange:'-',
		ultrasonic: '-',
		transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
	},

	{
		//Eagle60AP-LD
		machineName: 'Eagle60AP-LD',
		machineImage: 'img/wb/ic/eagle60AP-LD.png',
		machineLink: '../html/Wire Bonders Products/Eagle60AP-LD.html',
		bondPlacement: '-',
		bondingArea: '-',
		loopTypes: '-',
		uPH: '-',
		xyResolution: '-',
		zResolution: '-',
		finePitchCapability: '-',
		loopHeightVariation: '-',
		wireLength: '-',
		wireCapacity: '-',
		opticsLensMagnification: '-',
		sScanVisionEngine: '-',
		recognitionRange: '-',
		referenceSystems: '-',
		cameraType: '-',
		depthOfField:'-',
		dieRotation:'-',
		xyMotorsType:'-',
		lfWidth: '-',
		lfLength: '-',
		lfThickness: '-',
		dieSiteIndexingPitch: '-',
		noOfMagazine: '-',
		noOfLevels: '-',
		magazineWidth: '-',
		magazineLength: '-',
		magazineHeight: '-',
		slotPitch: '-',
		spoolDiameter: '-',
		spoolWidth: '-',
		wireCount: '-',
		wireEnd: '-',
		driveMotorType: '-',
		wireClamp: '-',
		bondTimeRange:'-',
		ultrasonic: '-',
		transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
	},

	{
		//Eagle60AP
		machineName: 'Eagle60AP',
		machineImage: 'img/wb/ic/eagle60AP.png',
		machineLink: '../html/Wire Bonders Products/Eagle60AP.html',
		bondPlacement: '±2.5 µm @ 3 Sigma',
		bondingArea: '54mm x 65mm @ LF width < 72mm',
		loopTypes: '26  loop modes<br>(eg Q-loop, Sq-loop, J-loop, M-loop etc)',
		uPH: '60 ms for 2 mm wire',
		xyResolution: '200 nm',
		zResolution: '400 nm',
		finePitchCapability: 'Mass production : 40um BPP<br>Lab. level : 30um BPP',
		loopHeightVariation: '± 1mils',
		wireLength: '0.6 - 8 mm',
		wireCapacity: '3000',
		opticsLensMagnification: '5.5x/3.6x or 8x/3.6x',
		sScanVisionEngine: 'ASM MMX PRS which enables very fast PR with highly accurate and sophisticated pattern recognition algorithm',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: 'Die and lead',
		cameraType: 'CCD',
		depthOfField: '3.6X ( 320 µm) / 5.5X (120 µm) / 8X (100 µm)',
		dieRotation: '10 degree (programmable)',
		xyMotorsType: 'Multi-phase linear motor',
		lfWidth: '23 – 90 mm',
		lfLength: '140 - 295 mm',
		lfThickness: '0.1 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: 'Typically 2-3 (depending on the magazine height)',
		noOfLevels: 'Programmable',
		magazineWidth: '100 mm',
		magazineLength: '140 - 300 mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '25 - 50 mm',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '0 - 20 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138kHz(std) with  64kHz & 100kHz as option',
		manMachineInterface: 'Menu',
		storageMedia: '3.5" Diskette and Harddisk ',
		powerInput: '50/60hz & 100/110/120/200/210/220/230/<br>240VAV (selectable)',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '5 bars',
		airConsumption: '120LPM @ 5 bars',
		airQuality: 'Particle size : 5mils(max)',
		environmentalRequirement: 'Clean room environment',
		machineOutline: '720mm (width) X 820mm (length) X 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Upgradable',
		easyCuConversion:'Yes',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},

	{
		//Eagle60
		machineName: 'Eagle60',
		machineImage: 'img/wb/ic/eagle60.png',
		machineLink: '../html/Wire Bonders Products/Eagle60.html',
		bondPlacement: '±3.0 µm @ 3 Sigma',
		bondingArea: '54mm x 65mm @ LF width < 72mm',
		loopTypes: '26  loop modes<br> (eg Q-loop, Sq-loop, J-loop, M-loop etc)',
		uPH: '65 ms for 2 mm wire',
		xyResolution: '200 nm',
		zResolution: '400 nm',
		finePitchCapability: 'Mass production : 50um BPP<br>Lab. level : 35um BPP',
		loopHeightVariation: '± 1mils',
		wireLength: '0.6 - 8 mm',
		wireCapacity: '3000',
		opticsLensMagnification: '5.5x/3.6x or 8x/3.6x',
		sScanVisionEngine: 'ASM MMX PRS which enables very fast PR with highly accurate and sophisticated pattern recognition algorithm',
		recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
		referenceSystems: 'Die and lead',
		cameraType: 'CCD',
		depthOfField: '3.6X ( 320 µm) / 5.5X (120 µm) / 8X (100 µm)',
		dieRotation: '10 degree (programmable)',
		xyMotorsType: 'Multi-phase linear motor',
		lfWidth: '23-72 mm without change of heater block<br>15-90mm with change of heater block',
		lfLength: 'Max 280 mm',
		lfThickness: '0.075 - 0.8 mm',
		dieSiteIndexingPitch: '-',
		noOfMagazine: 'Typically 2-3 (depending on the magazine height)',
		noOfLevels: 'Programmable',
		magazineWidth: '100 mm',
		magazineLength: '140 - 300 mm',
		magazineHeight: 'Max 180 mm',
		slotPitch: '2.4 - 10mm programmable',
		spoolDiameter:'50 mm',
		spoolWidth: '25 - 50 mm',
		wireCount: 'Yes',
		wireEnd: 'Yes',
		driveMotorType: 'Voice coil motor',
		wireClamp: 'Voice coil programmable',
		bondTimeRange: '0 - 20 ms',
		ultrasonic: 'Multi-mode with programmable BQM board',
		transducerFreq: '138kHz(std) with  64kHz & 100kHz as option',
		manMachineInterface: 'Menu',
		storageMedia: '3.5" Diskette and Harddisk ',
		powerInput: '50/60hz & 100/110/120/200/210/220/230/<br>240VAV (selectable)',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '5 bars',
		airConsumption: '120LPM @ 5 bars',
		airQuality: 'Particle size : 5mils(max)',
		environmentalRequirement: 'Clean room environment',
		machineOutline: '720mm (width) X 820mm (length) X 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'-',
		materialHandlingKits:'Host Communications via HSMS @ USD 2.5K per machine',
		heavyWireKit:'Bond program recipe transfer is within 30 secs (100M bit/sec)',
		illuminationKit:'NA',
		qfnKit:'OLP Editor software @ 30K (one time OLP capability charges)<br>and USD 10K (1st year only - OLP maintenance charges)',
		cuApplication:'Upgradable',
		easyCuConversion:'Yes',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},
	]; 

	optoMachines = [
	{
  	//iHawk Xpress XL
  	machineName: 'iHawk Xpress XL',
  	machineImage: 'img/wb/opto/ihawk-xpress-XL.png',
  	machineLink: '../html/Wire Bonders Products/iHawk Xpress XL.html',
  	bondPlacement: '-',
  	bondingArea: '-',
  	loopTypes: '-',
  	uPH: '-',
  	xyResolution: '-',
  	zResolution: '-',
  	finePitchCapability: '-',
  	loopHeightVariation: '-',
  	wireLength: '-',
  	wireCapacity: '-',
  	opticsLensMagnification: '-',
  	sScanVisionEngine: '-',
  	recognitionRange: '-',
  	referenceSystems: '-',
  	cameraType: '-',
  	depthOfField:'-',
  	dieRotation:'-',
  	xyMotorsType:'-',
  	lfWidth: '-',
  	lfLength: '-',
  	lfThickness: '-',
  	dieSiteIndexingPitch: '-',
  	noOfMagazine: '-',
  	noOfLevels: '-',
  	magazineWidth: '-',
  	magazineLength: '-',
  	magazineHeight: '-',
  	slotPitch: '-',
  	spoolDiameter: '-',
  	spoolWidth: '-',
  	wireCount: '-',
  	wireEnd: '-',
  	driveMotorType: '-',
  	wireClamp: '-',
  	bondTimeRange:'-',
  	ultrasonic: '-',
  	transducerFreq: '-',
  	manMachineInterface: '-',
  	storageMedia:'-',
  	powerInput:'-',   	
  	powerConsumption: '-',
  	minAirPressure: '-',
  	airConsumption: '-',
  	airQuality: '-',
  	environmentalRequirement: '-',
  	machineOutline: '-',
  	machineWeight: '-',
  	machineShippingWeight: '-',
  	indexers: '-',
  	materialHandlingKits: '-',
  	heavyWireKit: '-',
  	illuminationKit: '-',
  	qfnKit: '-',
  	cuApplication: '-',
  	easyCuConversion: '-',
  	smartPR: '-',
  	easyCuLooping: '-',
  	smartWire: '-',
  	autoWireRethread: '-',
  },

  {
   	//iHawk Xpress
   	machineName: 'iHawk Xpress',
   	machineImage: 'img/wb/opto/ihawk-xpress.png',
   	machineLink: '../html/Wire Bonders Products/iHawk Xpress.html',
   	bondPlacement: '-',
   	bondingArea: '-',
   	loopTypes: '-',
   	uPH: '-',
   	xyResolution: '-',
   	zResolution: '-',
   	finePitchCapability: '-',
   	loopHeightVariation: '-',
   	wireLength: '-',
   	wireCapacity: '-',
   	opticsLensMagnification: '-',
   	sScanVisionEngine: '-',
   	recognitionRange: '-',
   	referenceSystems: '-',
   	cameraType: '-',
   	depthOfField:'-',
   	dieRotation:'-',
   	xyMotorsType:'-',
   	lfWidth: '-',
   	lfLength: '-',
   	lfThickness: '-',
   	dieSiteIndexingPitch: '-',
   	noOfMagazine: '-',
   	noOfLevels: '-',
   	magazineWidth: '-',
   	magazineLength: '-',
   	magazineHeight: '-',
   	slotPitch: '-',
   	spoolDiameter: '-',
   	spoolWidth: '-',
   	wireCount: '-',
   	wireEnd: '-',
   	driveMotorType: '-',
   	wireClamp: '-',
   	bondTimeRange:'-',
   	ultrasonic: '-',
   	transducerFreq: '-',
   	manMachineInterface: '-',
   	storageMedia:'-',
   	powerInput:'-',   	
   	powerConsumption: '-',
   	minAirPressure: '-',
   	airConsumption: '-',
   	airQuality: '-',
   	environmentalRequirement: '-',
   	machineOutline: '-',
   	machineWeight: '-',
   	machineShippingWeight: '-',
   	indexers: '-',
   	materialHandlingKits: '-',
   	heavyWireKit: '-',
   	illuminationKit: '-',
   	qfnKit: '-',
   	cuApplication: '-',
   	easyCuConversion: '-',
   	smartPR: '-',
   	easyCuLooping: '-',
   	smartWire: '-',
   	autoWireRethread: '-',
   },

   {
   	//iHawk Xtreme-V
   	machineName: 'iHawk Xtreme-V',
   	machineImage: 'img/wb/opto/iHawk Xtreme-V.png',
   	machineLink: '../html/Wire Bonders Products/iHawk Xtreme-V.html',
   	bondPlacement: '-',
   	bondingArea: '-',
   	loopTypes: '-',
   	uPH: '-',
   	xyResolution: '-',
   	zResolution: '-',
   	finePitchCapability: '-',
   	loopHeightVariation: '-',
   	wireLength: '-',
   	wireCapacity: '-',
   	opticsLensMagnification: '-',
   	sScanVisionEngine: '-',
   	recognitionRange: '-',
   	referenceSystems: '-',
   	cameraType: '-',
   	depthOfField:'-',
   	dieRotation:'-',
   	xyMotorsType:'-',
   	lfWidth: '-',
   	lfLength: '-',
   	lfThickness: '-',
   	dieSiteIndexingPitch: '-',
   	noOfMagazine: '-',
   	noOfLevels: '-',
   	magazineWidth: '-',
   	magazineLength: '-',
   	magazineHeight: '-',
   	slotPitch: '-',
   	spoolDiameter: '-',
   	spoolWidth: '-',
   	wireCount: '-',
   	wireEnd: '-',
   	driveMotorType: '-',
   	wireClamp: '-',
   	bondTimeRange:'-',
   	ultrasonic: '-',
   	transducerFreq: '-',
   	manMachineInterface: '-',
   	storageMedia:'-',
   	powerInput:'-',   	
   	powerConsumption: '-',
   	minAirPressure: '-',
   	airConsumption: '-',
   	airQuality: '-',
   	environmentalRequirement: '-',
   	machineOutline: '-',
   	machineWeight: '-',
   	machineShippingWeight: '-',
   	indexers: '-',
   	materialHandlingKits: '-',
   	heavyWireKit: '-',
   	illuminationKit: '-',
   	qfnKit: '-',
   	cuApplication: '-',
   	easyCuConversion: '-',
   	smartPR: '-',
   	easyCuLooping: '-',
   	smartWire: '-',
   	autoWireRethread: '-',
   },

   {
   	//iHawk Xtreme
   	machineName: 'iHawk Xtreme',
   	machineImage: 'img/wb/opto/ihawk-xtreme.png',
   	machineLink: '../html/Wire Bonders Products/iHawk Xtreme.html',
   	bondPlacement: '± 3.0 µm @ 3 Sigma',
   	bondingArea: '56 mm x 70 mm (LF width <=80mm)<br> 56 mm x  "Y" mm, where  "Y" is equal to (150 - lead frame width) mm',
   	loopTypes: '52 loop modes (eg Q-Loop, Sq-Loop, J-Loop, M-Loop etc)',
   	uPH: '20 wires / sec (2mm wire)',
   	xyResolution: '100 nm',
   	zResolution: '200 nm',
   	finePitchCapability: '50 µm BPP',
   	loopHeightVariation: '3 - 16 mil',
   	wireLength: '0.6 - 8 mm',
   	wireCapacity: '3000',
   	opticsLensMagnification: 'Single optical path with 2-4X adjustable magnification',
   	sScanVisionEngine: '-',
   	recognitionRange: '± 2.5 mil<br>X & Y± 10°(programmable)',
   	referenceSystems: '-',
   	cameraType: 'CCD',
   	depthOfField:'326 µm @ 4X<br>600 µm @ 2X',
   	dieRotation:'-',
   	xyMotorsType:'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
   	lfWidth: '28 – 90 mm',
   	lfLength: '140 - 295 mm',
   	lfThickness: '0.1 - 0.8 mm',
   	dieSiteIndexingPitch: '-',
   	noOfMagazine: '3 (40 levels with 0.1" pitch / 2.54mm)',
   	noOfLevels: 'Programmable',
   	magazineWidth: '16 - 100 mm',
   	magazineLength: '140 - 295 mm',
   	magazineHeight: 'Max 180 mm',
   	slotPitch: '2.4 - 10 mm Programmable',
   	spoolDiameter: '50 mm',
   	spoolWidth: '50mm<br>25mm as option',
   	wireCount: 'Yes',
   	wireEnd: 'Yes',
   	driveMotorType: 'Voice coil motor',
   	wireClamp: 'Voice coil programmable',
   	bondTimeRange:'1 - 255 ms',
   	ultrasonic: 'Multi-mode with programmable BQM board',
   	transducerFreq: '138kHz',
   	manMachineInterface: 'Windows GUI display',
   	storageMedia:'-',
   	powerInput:'-',   	
   	powerConsumption: 'Max 1500W',
   	minAirPressure: '-',
   	airConsumption: '8 mm (ID)',
   	airQuality: '-',
   	environmentalRequirement: '-',
   	machineOutline: '720mm (width) X 820mm (length) X 1600mm (height)',
   	machineWeight: '750 Kg',
   	machineShippingWeight: '820 Kg',
   	indexers: 'Yes',
   	materialHandlingKits: '-',
   	heavyWireKit: 'NA',
   	illuminationKit: 'NA',
   	qfnKit: 'NA',
   	cuApplication: 'NA',
   	easyCuConversion: 'NA',
   	smartPR: 'NA',
   	easyCuLooping: 'NA',
   	smartWire: 'NA',
   	autoWireRethread: 'NA',
   },

   {
   	//Harrier Xtreme
   	machineName: 'Harrier Xtreme',
   	machineImage: 'img/wb/opto/ihawk-xtreme.png',
   	machineLink: '../html/Wire Bonders Products/Harrier Xtreme.html',
   	bondPlacement: '± 3.0 µm @ 3 Sigma',
   	bondingArea: '56 mm x 70 mm (LF width <=80mm)<br> 56 mm x  "Y" mm, where  "Y" is equal to (150 - lead frame width) mm',
   	loopTypes: '52 loop modes (eg Q-Loop, Sq-Loop, J-Loop, M-Loop etc)',
   	uPH: '20 wires / sec (2mm wire)',
   	xyResolution: '100 nm',
   	zResolution: '200 nm',
   	finePitchCapability: '50 µm BPP',
   	loopHeightVariation: '3 - 16 mil',
   	wireLength: 'Max 8 mm',
   	wireCapacity: '3000',
   	opticsLensMagnification: 'Single optical path with 2-4X adjustable magnification',
   	sScanVisionEngine: '-',
   	recognitionRange: '± 2.5 mil<br>X & Y± 10°(programmable)',
   	referenceSystems: '-',
   	cameraType: 'CCD',
   	depthOfField:'326 µm @ 4X<br>600 µm @ 2X',
   	dieRotation:'-',
   	xyMotorsType:'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
   	lfWidth: '28 – 90 mm',
   	lfLength: '140 - 295 mm',
   	lfThickness: '0.1 - 0.8 mm',
   	dieSiteIndexingPitch: '-',
   	noOfMagazine: '3 (40 levels with 0.1" pitch / 2.54mm)',
   	noOfLevels: 'Programmable',
   	magazineWidth: '16 - 100 mm',
   	magazineLength: '140 - 295 mm',
   	magazineHeight: 'Max 180 mm',
   	slotPitch: '2.4 - 10 mm Programmable',
   	spoolDiameter: '50 mm',
   	spoolWidth: '50mm<br>25mm as option',
   	wireCount: 'Yes',
   	wireEnd: 'Yes',
   	driveMotorType: 'Voice coil motor',
   	wireClamp: 'Voice coil programmable',
   	bondTimeRange:'1 - 255 ms',
   	ultrasonic: 'Multi-mode with programmable BQM board',
   	transducerFreq: '138kHz',
   	manMachineInterface: 'Windows GUI display',
   	storageMedia:'-',
   	powerInput:'-',   	
   	powerConsumption: '2000W',
   	minAirPressure: '-',
   	airConsumption: '8 mm (ID)',
   	airQuality: '-',
   	environmentalRequirement: '-',
   	machineOutline: '730mm (width) X 910mm (length) X 1450mm (height)',
   	machineWeight: '1020 Kg',
   	machineShippingWeight: '-',
   	indexers: 'Yes',
   	materialHandlingKits: '-',
   	heavyWireKit: 'NA',
   	illuminationKit: 'NA',
   	qfnKit: 'NA',
   	cuApplication: 'NA',
   	easyCuConversion: 'NA',
   	smartPR: 'NA',
   	easyCuLooping: 'NA',
   	smartWire: 'NA',
   	autoWireRethread: 'NA',
   },

   {
   	//iHawk-V
   	machineName: 'iHawk-V',
   	machineImage: 'img/wb/opto/ihawk-V.png',
   	machineLink: '../html/Wire Bonders Products/iHawk-V.html',
   	bondPlacement: '-',
   	bondingArea: '-',
   	loopTypes: '-',
   	uPH: '-',
   	xyResolution: '-',
   	zResolution: '-',
   	finePitchCapability: '-',
   	loopHeightVariation: '-',
   	wireLength: '-',
   	wireCapacity: '-',
   	opticsLensMagnification: '-',
   	sScanVisionEngine: '-',
   	recognitionRange: '-',
   	referenceSystems: '-',
   	cameraType: '-',
   	depthOfField:'-',
   	dieRotation:'-',
   	xyMotorsType:'-',
   	lfWidth: '-',
   	lfLength: '-',
   	lfThickness: '-',
   	dieSiteIndexingPitch: '-',
   	noOfMagazine: '-',
   	noOfLevels: '-',
   	magazineWidth: '-',
   	magazineLength: '-',
   	magazineHeight: '-',
   	slotPitch: '-',
   	spoolDiameter: '-',
   	spoolWidth: '-',
   	wireCount: '-',
   	wireEnd: '-',
   	driveMotorType: '-',
   	wireClamp: '-',
   	bondTimeRange:'-',
   	ultrasonic: '-',
   	transducerFreq: '-',
   	manMachineInterface: '-',
   	storageMedia:'-',
   	powerInput:'-',   	
   	powerConsumption: '-',
   	minAirPressure: '-',
   	airConsumption: '-',
   	airQuality: '-',
   	environmentalRequirement: '-',
   	machineOutline: '-',
   	machineWeight: '-',
   	machineShippingWeight: '-',
   	indexers: '-',
   	materialHandlingKits: '-',
   	heavyWireKit: '-',
   	illuminationKit: '-',
   	qfnKit: '-',
   	cuApplication: '-',
   	easyCuConversion: '-',
   	smartPR: '-',
   	easyCuLooping: '-',
   	smartWire: '-',
   	autoWireRethread: '-',
   },

      {
   	//HummingBird
   	machineName: 'HummingBird',
   	machineImage: 'img/wb/opto/hummingbird.png',
   	machineLink: '../html/Wire Bonders Products/HummingBird.html',
   	bondPlacement: '± 3.5 µm @ 3 Sigma',
   	bondingArea: '304.8 mm x 304.8 mm',
   	loopTypes: '-',
   	uPH: '30 bumps per sec for 1.0 mil Au wire (cycle time)',
   	xyResolution: 'Linear encoder with 0.2 micron resolution',
   	zResolution: 'Encoder with 0.2 micron resolution',
   	finePitchCapability: 'Encoder with 0.2 micron resolution',
   	loopHeightVariation: '-',
   	wireLength: '-',
   	wireCapacity: '-',
   	opticsLensMagnification: '3.5X / 8X',
   	sScanVisionEngine: '-',
   	recognitionRange: '± 2.5 mil<br>X & Y± 10°(programmable)',
   	referenceSystems: '-',
   	cameraType: 'CCD',
   	depthOfField:'3.5X (120 µm) / 8X (100 µm)',
   	dieRotation:'10 degree (programmable)',
   	xyMotorsType:'-',
   	lfWidth: '-',
   	lfLength: '-',
   	lfThickness: '-',
   	dieSiteIndexingPitch: '-',
   	noOfMagazine: '-',
   	noOfLevels: '-',
   	magazineWidth: '-',
   	magazineLength: '-',
   	magazineHeight: '-',
   	slotPitch: '-',
   	spoolDiameter: '50 mm',
   	spoolWidth: '25 - 50 mm',
   	wireCount: 'Yes',
   	wireEnd: 'Yes',
   	driveMotorType: 'Voice coil motor',
   	wireClamp: 'Voice coil programmable',
   	bondTimeRange:'0 - 20 ms',
   	ultrasonic: 'Multi-mode with programmable BQM board',
   	transducerFreq: '138kHz',
   	manMachineInterface: 'Bi - Lingual Man Machine Interface Host Communications via SECS 1 & 2 Protocol',
   	storageMedia:'-',
   	powerInput:'-',   	
   	powerConsumption: 'Max 1700 W',
   	minAirPressure: '5 bars',
   	airConsumption: '150 LPM @ 5 bars',
   	airQuality: '-',
   	environmentalRequirement: 'Clean room environment',
   	machineOutline: '1090 mm (width) x 1095 mm (length) x 1875 mm (height)',
   	machineWeight: '900 Kg',
   	machineShippingWeight: '-',
   	indexers: '-',
   	materialHandlingKits: '-',
   	heavyWireKit: 'NA',
   	illuminationKit: 'NA',
   	qfnKit: 'NA',
   	cuApplication: 'NA',
   	easyCuConversion: 'NA',
   	smartPR: 'NA',
   	easyCuLooping: 'NA',
   	smartWire: 'NA',
   	autoWireRethread: 'NA',
   },

   	//XKV-plus
   	machineName: 'XKV-plus',
   	machineImage: 'img/wb/opto/xkv-plus.png',
   	machineLink: '../html/Wire Bonders Products/XKV-Plus.html',
   	bondPlacement: '-',
   	bondingArea: '-',
   	loopTypes: '-',
   	uPH: '-',
   	xyResolution: '-',
   	zResolution: '-',
   	finePitchCapability: '-',
   	loopHeightVariation: '-',
   	wireLength: '-',
   	wireCapacity: '-',
   	opticsLensMagnification: '-',
   	sScanVisionEngine: '-',
   	recognitionRange: '-',
   	referenceSystems: '-',
   	cameraType: '-',
   	depthOfField:'-',
   	dieRotation:'-',
   	xyMotorsType:'-',
   	lfWidth: '-',
   	lfLength: '-',
   	lfThickness: '-',
   	dieSiteIndexingPitch: '-',
   	noOfMagazine: '-',
   	noOfLevels: '-',
   	magazineWidth: '-',
   	magazineLength: '-',
   	magazineHeight: '-',
   	slotPitch: '-',
   	spoolDiameter: '-',
   	spoolWidth: '-',
   	wireCount: '-',
   	wireEnd: '-',
   	driveMotorType: '-',
   	wireClamp: '-',
   	bondTimeRange:'-',
   	ultrasonic: '-',
   	transducerFreq: '-',
   	manMachineInterface: '-',
   	storageMedia:'-',
   	powerInput:'-',   	
   	powerConsumption: '-',
   	minAirPressure: '-',
   	airConsumption: '-',
   	airQuality: '-',
   	environmentalRequirement: '-',
   	machineOutline: '-',
   	machineWeight: '-',
   	machineShippingWeight: '-',
   	indexers: '-',
   	materialHandlingKits: '-',
   	heavyWireKit: '-',
   	illuminationKit: '-',
   	qfnKit: '-',
   	cuApplication: '-',
   	easyCuConversion: '-',
   	smartPR: '-',
   	easyCuLooping: '-',
   	smartWire: '-',
   	autoWireRethread: '-',
   },


   ];