machineFields = ['ID','Machine Name', 'Machine Image', 'Machine Link', 'Bond Placement Repeatability','Bonding Area','Loop Types', 'UPH', 'XY Resolution', 'Z Resolution', 'Fine Pitch Capability', 'Loop Height Variation', 'Wire Length', 'Wire Capacity', 'Optics Lens Magnification', 'S-Scan Vision Engine', 'Recognition Range', 'Reference Systems', 'Camera Type', 'Depth Of Field', 'Die Rotation', 'XY Motors Type', 'L/F Width', 'L/F Length', 'L/F Thickness', 'Die Site Indexing Pitch', 'No.of Magazine', 'No. of Levels', 'Magazine Width', 'Magazine Length', 'Magazine Height', 'Slot Pitch (Range of Pitch)', 'Spool Diameter', 'Spool Width', 'Wire Count', 'Wire End', 'Drive Motor Type', 'Wire Clamp', 'Bond Time Range', 'Ultrasonic Mode', 'Transducer Frequency', 'Man Machine Interface', 'Storage Media', 'Power Input', 'Power Consumption', 'Minimum Air Pressure', 'Air Consumption', 'Air Quality', 'Environmental Requirement', 'Machine Outline', 'Machine Weight', 'Machine Shipping Weight', 'Indexers', 'Material Handling Kits', 'Heavy Wire Kit', 'Illumination Kit', 'QFN Kit', 'Cu Application', 'Easy CU Conversion', 'Smart PR', 'Easy Cu Looping', 'Smart Wire Handler', 'Auto Wire Rethread'];

icMachines = [
	{
		//eagleAERO
		machineName: 'Eagle AERO',
	    machineImage: 'img/wb/ic/eagleAero.png',
	    machineLink: '../html/Wire Bonders Products/Eagle Aero.html',
	    bondPlacement: '±2.0 µm @ 3-sigma',
	    bondingArea: '56mm x 90mm (LF width <=100mm)',
	    loopTypes: 'ECP Loop Profile up to 15 kinks',
	    uPH: '24 wires/sec for 2mm',
	    xyResolution: '10 nm',
	    zResolution: '10 nm',
	    finePitchCapability: '30 µm BPP',
	    loopHeightVariation: '2 mil (Ultra Low Loop) - 16 mil',
	    wireLength: '0.2 - 8 mm',
	    wireCapacity: 'Up to 10000 for Step Repeat Matrix',
	    opticsLensMagnification: 'Programmable Focus:<br>Dual optical path 8X and 2X <br>PR Look-Ahead:<br>Dual optical path 5.2X and 1X',
	    sScanVisionEngine: '-',
	    recognitionRange: '± 2.5 mil<br>X & Y± 10°(programmable)',
	    referenceSystems: '-',
	    cameraType: 'CCD',
	    depthOfField:'-',
	    dieRotation:'-',
	    xyMotorsType:'Multi-phase linear motor and fully programmable(Handle multi-type devices)',
	   	lfWidth:'28 - 105 mm',
	   	lfLength:'140 - 300mm',
	   	lfThickness:'0.1 - 0.8 mm',
	   	dieSiteIndexingPitch:'-',
	   	noOfMagazine:'3 (40 levels with 0.1" pitch / 2.54mm)',
	   	noOfLevels:'Programmable',
	   	magazineWidth:'32 - 115 mm',
	   	magazineLength:'140 - 30 5mm',
	   	magazineHeight:'180 mm (max)',
	   	slotPitch:'2.4 - 10mm programmable',
	   	spoolDiameter:'50 mm',
	   	spoolWidth:'50 mm<br>25mm as option',
	   	wireCount:'Yes',
	   	wireEnd:'Yes',
	   	driveMotorType:'Voice coil motor',
	   	wireClamp:'Piezo driven, pivot-less mechanism',
	   	bondTimeRange:'-',
	   	ultrasonic:'Constant Current, Constant Voltage, Constant Power',
	   	transducerFreq:'Dual frequencies',
		manMachineInterface:'Windows-based GUI',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption:'1200 VA / 1200 Watt',
		minAirPressure:'-',
		airConsumption:'minimum 5 BAR, 150 lpm, Inlet tube OD 12mm',
		airQuality:'-',
		environmentalRequirement:'-',
		machineOutline:'1200mm (width) x 990mm (length) x 1760mm (height)',
		machineWeight:'800 Kg',
		machineShippingWeight:'-',
		indexers:'Yes',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'NA',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},
		
	{
		//ihawkAERO		
		machineName: 'iHawk AERO',
	    machineImage: 'img/wb/ic/ihawk-aero.png',
	    machineLink: '../html/Wire Bonders Products/iHawk Aero.html',
	    bondPlacement: '±2.0 µm @ 3-sigma',
	    bondingArea: '56mm x 90mm (LF width <=100mm)',
	    loopTypes: 'ECP Loop Profile up to 15 kinks',
	    uPH: '24 wires/sec for 2mm',
	    xyResolution: '10 nm',
	    zResolution: '10 nm',
	    finePitchCapability: '-',
	    loopHeightVariation: '2 mil (Ultra Low Loop) - 16 mil',
	    wireLength: '0.2 - 8 mm',
	    wireCapacity: 'Up to 10000 for Step Repeat Matrix',
	    opticsLensMagnification: 'Dual optical path 5.2X and 1X',
	    sScanVisionEngine: '-',
	    recognitionRange: '±2.5 mil<br>X & Y± 10°(programmable)',
	    referenceSystems: '-',
	    cameraType: 'CCD',
	    depthOfField:'-',
	    dieRotation:'-',
	    xyMotorsType:'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
	   	lfWidth:'28 - 105 mm',
	   	lfLength:'140 - 300mm',
	   	lfThickness:'0.1 - 0.8 mm',
	   	dieSiteIndexingPitch:'-',
	   	noOfMagazine:'3 (40 levels with 0.1" pitch / 2.54mm)',
	   	noOfLevels:'Programmable',
	   	magazineWidth:'32 - 115 mm',
	   	magazineLength:'140 - 305mm',
	   	magazineHeight:'180 mm (max)',
	   	slotPitch:'2.4 - 10mm programmable',
	   	spoolDiameter:'50 mm',
	   	spoolWidth:'50 mm<br>25mm as option',
	   	wireCount:'Yes',
	   	wireEnd:'Yes',
	   	driveMotorType:'Voice coil motor',
	   	wireClamp:'Piezo driven, pivot-less mechanism',
	   	bondTimeRange:'-',
	   	ultrasonic:'Constant Current, Constant Voltage, Constant Power',
	   	transducerFreq:'Dual frequencies',
		manMachineInterface:'Windows-based GUI',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption:'1200 VA / 1200 Watt',
		minAirPressure:'-',
		airConsumption:'minimum 5 BAR, 150 lpm, Inlet tube OD 12mm',
		airQuality:'-',
		environmentalRequirement:'-',
		machineOutline:'1200mm (width) x 990mm (length) x 1760mm (height)',
		machineWeight:'800 Kg',
		machineShippingWeight:'-',
		indexers:'Yes',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'NA',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//twineagleXpressGoCu	
		machineName: 'TwinEagle Xpress GoCu',
	    machineImage: 'img/wb/ic/twineagle-xpress-gocu.png',
	    machineLink: '../html/Wire Bonders Products/TwinEagle Xpress GoCu.html',
	    bondPlacement: 'PFM: ±2.0 µm @ 3-sigma<br>PRLA: ±3.0 µm @ 3-sigma',
	    bondingArea: '56mm x 90mm (LF width <=100mm)',
	    loopTypes: 'EasGo, EasiCu (Model Based)',
	    uPH: '20 wires/sec for 2mm',
	    xyResolution: '50 nm',
	    zResolution: '40 nm',
	    finePitchCapability: '30 µm BPP (Au)<br>40 µm BPP (Cu)',
	    loopHeightVariation: '2.0 - 16.0 mil',
	    wireLength: '0.6 - 7 mm',
	    wireCapacity: 'Up to 5000',
	    opticsLensMagnification: 'PFM, Single & Dual path PRLA',
	    sScanVisionEngine: '-',
	    recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
	    referenceSystems: '-',
	    cameraType: 'CMOS',
	    depthOfField: '-',
	    dieRotation: '-',
	    xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
	   	lfWidth: '30 - 100 mm',
	   	lfLength: '140 - 300mm',
	   	lfThickness: '0.1 - 0.8 mm',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: '3 (40 levels with 0.1" pitch / 2.54mm)',
	   	noOfLevels: 'Programmable',
	   	magazineWidth: '30 - 105 mm',
	   	magazineLength: '140 - 305mm',
	   	magazineHeight: '55 - 180 mm',
	   	slotPitch: '2.4 - 10mm programmable',
	   	spoolDiameter:'50 mm',
	   	spoolWidth: '50 mm<br>25mm as option',
	   	wireCount: 'Yes',
	   	wireEnd: 'Yes',
	   	driveMotorType: 'Voice coil motor',
	   	wireClamp: 'Voice coil programmable',
	   	bondTimeRange: '1 - 255 ms',
	   	ultrasonic: 'Multi-mode with programmable BQM board',
	   	transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 2000W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '960mm (width) x 1320mm (length) x 2100mm (height)',
		machineWeight:'1050 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'Yes',
		smartPR:'Yes',
		easyCuLooping:'NA',
		smartWire:'Yes',
		autoWireRethread:'Capable',
	},

	{
		//iHawk Xpress GoCu
		machineName: 'iHawk Xpress GoCu',
	    machineImage: 'img/wb/ic/ihawk-xpress-gocu.png',
	    machineLink: '../html/Wire Bonders Products/iHawk Xpress GoCu.html',
	    bondPlacement: '3.0 µm @ 3-sigma',
	    bondingArea: '56mm x 90mm (LF width <=100mm)',
	    loopTypes: 'New looping modes (eg Easi 1st kink, 2nd kinks etc.) ',
	    uPH: '20 wires/sec for 2mm',
	    xyResolution: '50 nm',
	    zResolution: '40 nm',
	    finePitchCapability: '50 µm BPP',
	    loopHeightVariation: '3 - 16 mil',
	    wireLength: 'Max 8 mm',
	    wireCapacity: 'Up to 5000',
	    opticsLensMagnification: 'Single path optics, 2x- 4x adjustable magnification<br>Dual path optics as option',
	    sScanVisionEngine: '-',
	    recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
	    referenceSystems: '-',
	    cameraType: 'CCD',
	    depthOfField: '-',
	    dieRotation: '-',
	    xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
	   	lfWidth: '30 - 100 mm',
	   	lfLength: '140 - 300mm',
	   	lfThickness: '0.1 - 0.8 mm',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: 'Typically 2-3',
	   	noOfLevels: 'Programmable',
	   	magazineWidth: '30 - 105 mm',
	   	magazineLength: '140 - 305mm',
	   	magazineHeight: 'Max. 180 mm',
	   	slotPitch: '2.4 - 10mm programmable',
	   	spoolDiameter:'50 mm',
	   	spoolWidth: '50 mm<br>25mm as option',
	   	wireCount: 'Yes',
	   	wireEnd: 'Yes',
	   	driveMotorType: 'Voice coil motor',
	   	wireClamp: 'Voice coil programmable',
	   	bondTimeRange: '1 - 255 ms',
	   	ultrasonic: 'Multi-mode with programmable BQM board',
	   	transducerFreq: '138 kHz',
		manMachineInterface: 'Multi-Lingual',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 820mm (length) x 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'Yes',
		smartPR:'Yes',
		easyCuLooping:'NA',
		smartWire:'Yes',
		autoWireRethread:'Capable',
	},

		{
		//Eagle Xpress GoCu
		machineName: 'Eagle Xpress GoCu',
	    machineImage: 'img/wb/ic/eagle-xpress-gocu.png',
	    machineLink: '../html/Wire Bonders Products/Eagle Xpress GoCu.html',
	    bondPlacement: '±2.0 µm @ 3-sigma',
	    bondingArea: '56mm x 90mm (LF width <=100mm)',
	    loopTypes: 'New looping modes (eg Easi 1st kink, 2nd kinks etc.) ',
	    uPH: '20 wires/sec for 2mm',
	    xyResolution: '50 nm',
	    zResolution: '40 nm',
	    finePitchCapability: '30 µm BPP',
	    loopHeightVariation: '3 - 16 mil',
	    wireLength: '0.6 - 7 mm',
	    wireCapacity: '3000',
	    opticsLensMagnification: 'Programmable Focus Optics 8X and 2.0X',
	    sScanVisionEngine: '-',
	    recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
	    referenceSystems: '-',
	    cameraType: 'CCD',
	    depthOfField: '-',
	    dieRotation: '-',
	    xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
	   	lfWidth: '30 - 105 mm',
	   	lfLength: '140 - 300mm',
	   	lfThickness: '0.1 - 0.8 mm',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: '3 (40 levels with 0.1" pitch / 2.54mm)',
	   	noOfLevels: 'Programmable',
	   	magazineWidth: '30 - 105 mm',
	   	magazineLength: '140 - 305mm',
	   	magazineHeight: '55 - 180 mm',
	   	slotPitch: '2.4 - 10mm programmable',
	   	spoolDiameter:'50 mm',
	   	spoolWidth: '50 mm<br>25mm as option',
	   	wireCount: 'Yes',
	   	wireEnd: 'Yes',
	   	driveMotorType: 'Voice coil motor',
	   	wireClamp: 'Voice coil programmable',
	   	bondTimeRange: '1 - 255 ms',
	   	ultrasonic: 'Multi-mode with programmable BQM board',
	   	transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 820mm (length) x 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'820 Kg',
		indexers:'Yes',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Available',
		easyCuConversion:'Yes',
		smartPR:'Yes',
		easyCuLooping:'Yes',
		smartWire:'Yes',
		autoWireRethread:'Capable',
	},

	{
		//TwinEagle Xtreme GoCu
		machineName: 'TwinEagle Xtreme GoCu',
	    machineImage: 'img/wb/ic/eagle-xpress-gocu.png',
	    machineLink: '../html/Wire Bonders Products/Eagle Xpress GoCu.html',
	    bondPlacement: 'PFM: ±2.0 mm @ 3 Sigma<br>PRLA: ±3.0 mm @ 3 Sigma',
	    bondingArea: '56mm x 70mm (LF width<=80mm)',
	    loopTypes: 'EasGo, EasiCu ( Model Based )',
	    uPH: '20 wires/sec for 2mm',
	    xyResolution: '50 nm',
	    zResolution: '100 nm',
	    finePitchCapability: '30 µm BPP',
	    loopHeightVariation: '2 - 16 mil',
	    wireLength: 'Max 8 mm',
	    wireCapacity: 'Up to 5000',
	    opticsLensMagnification: '-',
	    sScanVisionEngine: '-',
	    recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
	    referenceSystems: '-',
	    cameraType: 'CMOS',
	    depthOfField: '-',
	    dieRotation: '-',
	    xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
	   	lfWidth: '29 - 90 mm',
	   	lfLength: '140 - 240mm',
	   	lfThickness: '0.1 - 0.8 mm',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: '3 (40 levels with 0.1" pitch / 2.54mm)',
	   	noOfLevels: 'Programmable',
	   	magazineWidth: '30 - 100 mm',
	   	magazineLength: '140 - 295mm',
	   	magazineHeight: '55 - 180 mm',
	   	slotPitch: '2.4 - 10mm programmable',
	   	spoolDiameter:'50 mm',
	   	spoolWidth: '50 mm<br>25mm as option',
	   	wireCount: 'Yes',
	   	wireEnd: 'Yes',
	   	driveMotorType: 'Voice coil motor',
	   	wireClamp: 'Voice coil programmable',
	   	bondTimeRange: '1 - 255 ms',
	   	ultrasonic: 'Multi-mode with programmable BQM board',
	   	transducerFreq: '138 kHz',
		manMachineInterface: 'Multi-Lingual',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 960mm (length) x 1600mm (height)',
		machineWeight:'1020 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'Yes',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'Yes',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//iHawk Xtreme GoCu
		machineName: 'iHawk Xtreme GoCu',
	    machineImage: 'img/wb/ic/ihawk-xtreme-gocu.png',
	    machineLink: '../html/Wire Bonders Products/iHawk Xtreme GoCu.html',
	    bondPlacement: '±2.0 µm @ 3 Sigma',
	    bondingArea: '56mm x 70mm (LF width<=80mm)',
	    loopTypes: '-',
	    uPH: '20 wires/sec for 2mm',
	    xyResolution: '100 nm',
	    zResolution: '200 nm',
	    finePitchCapability: '-',
	    loopHeightVariation: '-',
	    wireLength: 'Max 8 mm',
	    wireCapacity: 'Up to 5000',
	    opticsLensMagnification: '-',
	    sScanVisionEngine: '-',
	    recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
	    referenceSystems: '-',
	    cameraType: 'CMOS',
	    depthOfField: '-',
	    dieRotation: '-',
	    xyMotorsType: '-',
	   	lfWidth: '23 - 90 mm',
	   	lfLength: '140 - 295mm',
	   	lfThickness: '0.1 - 0.8 mm',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: 'Typically 2-3',
	   	noOfLevels: '-',
	   	magazineWidth: '30 - 100 mm',
	   	magazineLength: '140 - 295mm',
	   	magazineHeight: '55 - 180 mm',
	   	slotPitch: '2.4 - 10mm programmable',
	   	spoolDiameter:'-',
	   	spoolWidth: '-',
	   	wireCount: '-',
	   	wireEnd: '-',
	   	driveMotorType: '-',
	   	wireClamp: '-',
	   	bondTimeRange: '-',
	   	ultrasonic: '-',
	   	transducerFreq: 'Mode A: 138kHz<br>Mode B: 73kHz',
		manMachineInterface: 'Multi-Lingual',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 820mm (length) x 1600mm (height)',
		machineWeight:'750 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//Harrier Xtreme GoCu
		machineName: 'Harrier Xtreme GoCu',
	    machineImage: 'img/wb/ic/harrier-xtreme-gocu.png',
	    machineLink: '../html/Wire Bonders Products/Harrier Xtreme GoCu.html',
	    bondPlacement: '±2.0 µm @ 3 Sigma',
	    bondingArea: '56mm x 70mm (LF width<=80mm)',
	    loopTypes: '-',
	    uPH: '20 wires/sec for 2mm',
	    xyResolution: '100 nm',
	    zResolution: '200 nm',
	    finePitchCapability: '-',
	    loopHeightVariation: '-',
	    wireLength: 'Max 8 mm',
	    wireCapacity: 'Up to 5000',
	    opticsLensMagnification: '-',
	    sScanVisionEngine: '-',
	    recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
	    referenceSystems: '-',
	    cameraType: '-',
	    depthOfField: '-',
	    dieRotation: '-',
	    xyMotorsType: '-',
	   	lfWidth: '23 - 90 mm',
	   	lfLength: '140 - 240mm',
	   	lfThickness: '0.1 - 0.8 mm',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: 'Typically 2-3',
	   	noOfLevels: '-',
	   	magazineWidth: '30 - 100 mm',
	   	magazineLength: '140 - 295mm',
	   	magazineHeight: '55 - 180 mm',
	   	slotPitch: '2.4 - 10mm programmable',
	   	spoolDiameter:'-',
	   	spoolWidth: '-',
	   	wireCount: '-',
	   	wireEnd: '-',
	   	driveMotorType: '-',
	   	wireClamp: '-',
	   	bondTimeRange: '-',
	   	ultrasonic: '-',
	   	transducerFreq: 'Mode A: 138kHz<br>Mode B: 73kHz',
		manMachineInterface: 'Multi-Lingual',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 2000W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 960mm (length) x 1600mm (height)',
		machineWeight:'1020 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},

	{
		//Eagle Xtreme GoCu
		machineName: 'Eagle Xtreme GoCu',
	    machineImage: 'img/wb/ic/eagle-xtreme-gocu.png',
	    machineLink: '../html/Wire Bonders Products/Eagle Xtreme GoCu.html',
	    bondPlacement: 'PFM: ±2.0 µm @ 3 Sigma<br>PRLA: ±3.0µm @ 3 Sigma',
	    bondingArea: '56mm x 70mm (LF width<=80mm)',
	    loopTypes: '-',
	    uPH: '20 wires/sec for 2mm',
	    xyResolution: '50 nm',
	    zResolution: '100 nm',
	    finePitchCapability: '30 µm BPP (Au)<br>40 µm BPP (Cu)',
	    loopHeightVariation: '2 - 16 mil',
	    wireLength: '0.6 - 7 mm',
	    wireCapacity: 'Up to 5000',
	    opticsLensMagnification: '-',
	    sScanVisionEngine: '-',
	    recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
	    referenceSystems: '-',
	    cameraType: 'CMOS',
	    depthOfField: '-',
	    dieRotation: '-',
	    xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
	   	lfWidth: '23 - 90 mm',
	   	lfLength: '140 - 295mm',
	   	lfThickness: '0.1 - 0.8 mm',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
	   	noOfLevels: '-',
	   	magazineWidth: '30 - 100 mm',
	   	magazineLength: '140 - 295mm',
	   	magazineHeight: 'Max 180 mm',
	   	slotPitch: '2.4 - 10mm programmable',
	   	spoolDiameter:'50 mm',
	   	spoolWidth: '50 mm<br>25 mm as option',
	   	wireCount: 'Yes',
	   	wireEnd: 'Yes',
	   	driveMotorType: 'Voice coil motor',
	   	wireClamp: 'Voice coil programmable',
	   	bondTimeRange: '1 - 255 ms',
	   	ultrasonic: 'Multi-mode with programmable BQM board',
	   	transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: 'Max 1500W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '720mm (width) x 820mm (length) x 1600mm (height)',
		machineWeight:'730 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'Capable',
	},


	{
		//Eagle Xpress
		machineName: 'Eagle Xpress',
	    machineImage: 'img/wb/ic/eagle-xpress.png',
	    machineLink: '../html/Wire Bonders Products/Eagle Xpress.html',
	   	bondPlacement: '-',
	    bondingArea: '-',
	    loopTypes: '-',
	    uPH: '-',
	    xyResolution: '-',
	    zResolution: '-',
	    finePitchCapability: '-',
	    loopHeightVariation: '-',
	    wireLength: '-',
	    wireCapacity: '-',
	    opticsLensMagnification: '-',
	    sScanVisionEngine: '-',
	    recognitionRange: '-',
	    referenceSystems: '-',
	    cameraType: '-',
	    depthOfField:'-',
	    dieRotation:'-',
	    xyMotorsType:'-',
	   	lfWidth: '-',
	   	lfLength: '-',
	   	lfThickness: '-',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: '-',
	   	noOfLevels: '-',
	   	magazineWidth: '-',
	   	magazineLength: '-',
	   	magazineHeight: '-',
	   	slotPitch: '-',
	   	spoolDiameter: '-',
	   	spoolWidth: '-',
	   	wireCount: '-',
	   	wireEnd: '-',
	   	driveMotorType: '-',
	   	wireClamp: '-',
	   	bondTimeRange:'-',
	   	ultrasonic: '-',
	   	transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
		},

	{
		//TwinEagle Xtreme
		machineName: 'TwinEagle Xtreme',
	    machineImage: 'img/wb/ic/twineagle-xtreme.png',
	    machineLink: '../html/Wire Bonders Products/TwinEagle Xtreme.html',
	    bondPlacement: '±2.0 µm @ 3 Sigma',
	    bondingArea: ' 56mm x 70mm (LF width<=80mm)<br>56mm x "Y" mm, where "Y" is equal to (150 - lead frame width) mm',
	    loopTypes: '52 loop modes (eg Q-Loop, Sq-Loop, J-Loop, M-Loop etc)',
	    uPH: '20 wires/sec for 2mm',
	    xyResolution: '50 nm',
	    zResolution: '100 nm',
	    finePitchCapability: '30 µm BPP',
	    loopHeightVariation: '3 - 16 mil',
	    wireLength: '0.6 - 8 mm',
	    wireCapacity: '3000 (standard)',
	    opticsLensMagnification: 'Dual optical path 8X and 2.0X<br>5.5 X and 2.0X as option',
	    sScanVisionEngine: '-',
	    recognitionRange: 'X & Y ±2.5 mil<br>X & Y ±10° (programmable)',
	    referenceSystems: '-',
	    cameraType: 'CCD',
	    depthOfField: '100 µm @ 8X<br>500 µm @ 2.0X<br>120 µm @ 5.5X as option',
	    dieRotation: '-',
	    xyMotorsType: 'Multi-phase linear motor and fully programmable (Handle multi-type devices)',
	   	lfWidth: '28 - 90 mm',
	   	lfLength: '140 - 295mm',
	   	lfThickness: '0.1 - 0.8 mm',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: '3 (40 levels with 0.1” pitch / 2.54 mm)',
	   	noOfLevels: 'Programmable',
	   	magazineWidth: '30 - 100 mm',
	   	magazineLength: '140 - 295mm',
	   	magazineHeight: 'Max 8 mm',
	   	slotPitch: '2.4 - 10mm programmable',
	   	spoolDiameter:'50 mm',
	   	spoolWidth: '50 mm<br>25 mm as option',
	   	wireCount: 'Yes',
	   	wireEnd: 'Yes',
	   	driveMotorType: 'Voice coil motor',
	   	wireClamp: 'Voice coil programmable',
	   	bondTimeRange: '1 - 255 ms',
	   	ultrasonic: 'Multi-mode with programmable BQM board',
	   	transducerFreq: '138 kHz',
		manMachineInterface: 'Windows GUI display',
		storageMedia: '-',
		powerInput: '-',   	
		powerConsumption: '2000W',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '730mm (width) x 910mm (length) x 1450mm (height)',
		machineWeight:'1020 Kg',
		machineShippingWeight:'-',
		indexers:'-',
		materialHandlingKits:'-',
		heavyWireKit:'NA',
		illuminationKit:'NA',
		qfnKit:'NA',
		cuApplication:'Yes',
		easyCuConversion:'NA',
		smartPR:'NA',
		easyCuLooping:'NA',
		smartWire:'NA',
		autoWireRethread:'NA',
	},

	{
		//Eagle Xtreme X2L
		machineName: 'Eagle Xtreme X2L',
	    machineImage: 'img/wb/ic/eagle-xtreme-X2L.png',
	    machineLink: '../html/Wire Bonders Products/Eagle Xtreme X2L.html',
	   	bondPlacement: '-',
	    bondingArea: '-',
	    loopTypes: '-',
	    uPH: '-',
	    xyResolution: '-',
	    zResolution: '-',
	    finePitchCapability: '-',
	    loopHeightVariation: '-',
	    wireLength: '-',
	    wireCapacity: '-',
	    opticsLensMagnification: '-',
	    sScanVisionEngine: '-',
	    recognitionRange: '-',
	    referenceSystems: '-',
	    cameraType: '-',
	    depthOfField:'-',
	    dieRotation:'-',
	    xyMotorsType:'-',
	   	lfWidth: '-',
	   	lfLength: '-',
	   	lfThickness: '-',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: '-',
	   	noOfLevels: '-',
	   	magazineWidth: '-',
	   	magazineLength: '-',
	   	magazineHeight: '-',
	   	slotPitch: '-',
	   	spoolDiameter: '-',
	   	spoolWidth: '-',
	   	wireCount: '-',
	   	wireEnd: '-',
	   	driveMotorType: '-',
	   	wireClamp: '-',
	   	bondTimeRange:'-',
	   	ultrasonic: '-',
	   	transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
	},

	
	{
		//Eagle Xtreme R2R
		machineName: 'Eagle Xtreme R2R',
	    machineImage: 'img/wb/ic/eagle-xtreme-R2R.png',
	    machineLink: '../html/Wire Bonders Products/Eagle Xtreme R2R.html',
	   	bondPlacement: '-',
	    bondingArea: '-',
	    loopTypes: '-',
	    uPH: '-',
	    xyResolution: '-',
	    zResolution: '-',
	    finePitchCapability: '-',
	    loopHeightVariation: '-',
	    wireLength: '-',
	    wireCapacity: '-',
	    opticsLensMagnification: '-',
	    sScanVisionEngine: '-',
	    recognitionRange: '-',
	    referenceSystems: '-',
	    cameraType: '-',
	    depthOfField:'-',
	    dieRotation:'-',
	    xyMotorsType:'-',
	   	lfWidth: '-',
	   	lfLength: '-',
	   	lfThickness: '-',
	   	dieSiteIndexingPitch: '-',
	   	noOfMagazine: '-',
	   	noOfLevels: '-',
	   	magazineWidth: '-',
	   	magazineLength: '-',
	   	magazineHeight: '-',
	   	slotPitch: '-',
	   	spoolDiameter: '-',
	   	spoolWidth: '-',
	   	wireCount: '-',
	   	wireEnd: '-',
	   	driveMotorType: '-',
	   	wireClamp: '-',
	   	bondTimeRange:'-',
	   	ultrasonic: '-',
	   	transducerFreq: '-',
		manMachineInterface: '-',
		storageMedia:'-',
		powerInput:'-',   	
		powerConsumption: '-',
		minAirPressure: '-',
		airConsumption: '-',
		airQuality: '-',
		environmentalRequirement: '-',
		machineOutline: '-',
		machineWeight: '-',
		machineShippingWeight: '-',
		indexers: '-',
		materialHandlingKits: '-',
		heavyWireKit: '-',
		illuminationKit: '-',
		qfnKit: '-',
		cuApplication: '-',
		easyCuConversion: '-',
		smartPR: '-',
		easyCuLooping: '-',
		smartWire: '-',
		autoWireRethread: '-',
	},

]; 

optoMachines = [
  {
    machineName: 'iHawk Xpress XL',
    machineImage: 'img/wb/opto/ihawk-xpress-XL.png',
    machineLink: '../html/Wire Bonders Products/iHawk Xpress XL.html',
   	bondPlacement: '-',
    bondingArea: '-',
    loopTypes: '-',
    uPH: '-',
    xyResolution: '-',
    zResolution: '-',
    finePitchCapability: '-',
    loopHeightVariation: '-',
    wireLength: '-',
    wireCapacity: '-',
    opticsLensMagnification: '-',
    sScanVisionEngine: '-',
    recognitionRange: '-',
    referenceSystems: '-',
    cameraType: '-',
    depthOfField:'-',
    dieRotation:'-',
    xyMotorsType:'-',
   	lfWidth: '-',
   	lfLength: '-',
   	lfThickness: '-',
   	dieSiteIndexingPitch: '-',
   	noOfMagazine: '-',
   	noOfLevels: '-',
   	magazineWidth: '-',
   	magazineLength: '-',
   	magazineHeight: '-',
   	slotPitch: '-',
   	spoolDiameter: '-',
   	spoolWidth: '-',
   	wireCount: '-',
   	wireEnd: '-',
   	driveMotorType: '-',
   	wireClamp: '-',
   	bondTimeRange:'-',
   	ultrasonic: '-',
   	transducerFreq: '-',
	manMachineInterface: '-',
	storageMedia:'-',
	powerInput:'-',   	
	powerConsumption: '-',
	minAirPressure: '-',
	airConsumption: '-',
	airQuality: '-',
	environmentalRequirement: '-',
	machineOutline: '-',
	machineWeight: '-',
	machineShippingWeight: '-',
	indexers: '-',
	materialHandlingKits: '-',
	heavyWireKit: '-',
	illuminationKit: '-',
	qfnKit: '-',
	cuApplication: '-',
	easyCuConversion: '-',
	smartPR: '-',
	easyCuLooping: '-',
	smartWire: '-',
	autoWireRethread: '-',
  },

  ];